### ISSUE TITLE
Contact Page

### ISSUE THREAD

**Issue by smthomas** [smthomas/learncreatebuild#9]
Create the Contact Page on the website. This will need to use the Contact and Contact Storage modules.

- [ ] As a customer, I want to be able to go to the /contact page and fill out a contact form to get in touch with someone from Learn Create Build.
- [ ] As an LCB admin, I want to receive an email at hello@learncreatebuild.com anytime a contact form submission is created, I also want to be able view past contact form submission on the website.

**Comment by krcilr** [comment]
Initial code of this is done
